In [8]:
import numpy as np
import sympy
import tensorflow  as tf
from sympy import symbols
from sympy import simplify
from sympy.solvers import solve
from sympy.interactive.printing import init_printing
from sympy.matrices import Matrix, eye, zeros

In [82]:
a = np.random.normal(size=(3**9, 3**9)).astype('float32')
b = np.random.normal(size=(3**9, 1)).astype('float32')

expected = np.matmul(a, b)

In [84]:
def py_matmul(a, b):
    ra, ca = a.shape
    rb, cb = b.shape
    assert ca == rb, f"{ca} != {rb}"

    return np.matmul(a, b)

def py_tf(a, b):
    ra, ca = a.shape
    rb, cb = b.shape
    assert ca == rb, f"{ca} != {rb}"

    return tf.matmul(a, b)

def py_np(a, b):
    ra, ca = a.shape
    rb, cb = b.shape
    assert ca == rb, f"{ca} != {rb}"

    return a@b

def py_einsum(a, b):
    ra, ca = a.shape
    rb, cb = b.shape
    assert ca == rb, f"{ca} != {rb}"

    return np.einsum('ij,jk', a, b)
#assert result.shape == expected.shape
#assert np.allclose(result, expected, rtol=1e-02), (result, expected)

In [85]:
tf_a = tf.constant(a)
tf_b = tf.constant(b)
%time result = py_tf(tf_a, tf_b)

CPU times: total: 93.8 ms
Wall time: 124 ms


In [86]:
%time result = py_np(a, b)

CPU times: total: 359 ms
Wall time: 93.7 ms


In [87]:
%time result = py_matmul(a, b)

CPU times: total: 484 ms
Wall time: 98.7 ms


In [88]:
%time result = py_einsum(a, b)

CPU times: total: 172 ms
Wall time: 255 ms


In [117]:
a = np.random.random((60,60))
b = np.random.random((60,60))
ab = np.kron(a,b)
abe = np.einsum('ik,jl', a, b).reshape(3600,3600)

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [105]:
default_matrix = np.array([[0, 1, 0],
                          [1, 0, 0],
                          [0, 0, 1]], dtype=complex)

In [103]:
np.reshape(default_matrix, 1 * [2,2])

ValueError: cannot reshape array of size 9 into shape (2,2)

In [91]:
np.kron(default_matrix, np.eye(3))

array([[0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [13]:
init_printing(use_unicode=False, wrap_line=False)
phi1 = symbols("varphi_1")
phi2 = symbols("varphi_2")
phi3 = symbols("varphi_3")
phi4 = symbols("varphi_4")
phi5 = symbols("varphi_5")
theta1 = symbols("theta_1")
theta2 = symbols("theta_2")
theta3 = symbols("theta_3")
a, b, c, d, e, f, g, h, i = symbols("a b c d e f g h i")

In [13]:
U_matrix = Matrix([[a, b, c],
                   [d, e, f],
                   [g, h, i]]); U_matrix

[a  b  c]
[       ]
[d  e  f]
[       ]
[g  h  i]

In [14]:
M = Matrix([[sympy.exp(-1j * phi1 / 2), 0, 0],
                         [0, sympy.exp(1j * phi1 / 2), 0],
                         [0, 0, 1]])

In [38]:
U_D = Matrix([[sympy.exp(1j*phi1), 0, 0],
              [0, sympy.exp(1j*phi2), 0],
              [0, 0, sympy.exp(1j*phi3)]])
P01 =  Matrix([[sympy.exp(1j * theta1), 0, 0],
                [0, 1, 0],
                [0, 0, 1]])
P12 = Matrix([[1, 0, 0],
                [0, 1, 0],
                [0, 0, sympy.exp(1j * theta2)]])
Z01 = Matrix([[sympy.exp(-1j * phi4 / 2), 0, 0],
                [0, sympy.exp(1j * phi4 / 2), 0],
                [0, 0, 1]])
Z12 =  Matrix([[1, 0, 0],
            [0, sympy.exp(-1j * phi5 / 2), 0],
            [0, 0, sympy.exp(1j * phi5 / 2)]])

In [39]:
P = P01*P12; P

[ 1.0*I*theta_1                   ]
[e               0        0       ]
[                                 ]
[      0         1        0       ]
[                                 ]
[                    1.0*I*theta_2]
[      0         0  e             ]

In [40]:
Z = Z01*Z12*Z01*Z12; Z

[ -1.0*I*varphi_4                                                   ]
[e                                0                         0       ]
[                                                                   ]
[                   1.0*I*varphi_4  -1.0*I*varphi_5                 ]
[       0          e              *e                        0       ]
[                                                                   ]
[                                                     1.0*I*varphi_5]
[       0                         0                  e              ]

In [41]:
solution = solve(U_D-Z, [theta1, theta2])

In [42]:
solution

In [31]:
M1 = Matrix([[1, 0, 0],
            [0, sympy.exp(-1j * phi2 / 2), 0],
            [0, 0, sympy.exp(1j * phi2 / 2)]])

In [32]:
M2 = Matrix([[1, 0, 0],
            [0, sympy.cos(theta1 / 2), -sympy.sin(theta1 / 2)],
            [0, sympy.sin(theta1 / 2), sympy.cos(theta1 / 2)]])

In [33]:
M3 = Matrix([[sympy.cos(theta2 / 2), -sympy.sin(theta2 / 2), 0],
            [sympy.sin(theta2 / 2), sympy.cos(theta2 / 2), 0],
            [0, 0, 1]])

In [34]:
M4 = Matrix([[sympy.exp(-1j * phi3 / 2), 0, 0],
                         [0, sympy.exp(1j * phi3 / 2), 0],
                         [0, 0, 1]])

In [35]:
M5 = Matrix([[1, 0, 0],
            [0, sympy.exp(-1j * phi4 / 2), 0],
            [0, 0, sympy.exp(1j * phi4 / 2)]])

In [36]:
M6 = Matrix([[1, 0, 0],
            [0, sympy.cos(theta3 / 2), -sympy.sin(theta3 / 2)],
            [0, sympy.sin(theta3 / 2), sympy.cos(theta3 / 2)]])

In [37]:
M7 = Matrix([[sympy.exp(-1j * phi5 / 2), 0, 0],
                         [0, sympy.exp(1j * phi5 / 2), 0],
                         [0, 0, 1]])

In [38]:
M8 = Matrix([[1, 0, 0],
            [0, sympy.exp(-1j * 2*phi5 / 2), 0],
            [0, 0, sympy.exp(1j * 2*phi5 / 2)]])

In [39]:
U = M*M1*M2*M3*M4*M5*M6*M7*M8

In [43]:
U.applyfunc(simplify)

[            -0.5*I*(varphi_1 + varphi_3 + varphi_5)    /theta_2\                                                                                -0.5*I*(varphi_1 - varphi_3 + varphi_4 + varphi_5)    /theta_2\    /theta_3\                                                                                                                             I*(-0.5*varphi_1 + 0.5*varphi_3 - 0.5*varphi_4 + 1.0*varphi_5)    /theta_2\    /theta_3\                                                         ]
[           e                                       *cos|-------|                                                                              -e                                                  *sin|-------|*cos|-------|                                                                                                                            e                                                              *sin|-------|*sin|-------|                                                         ]
[             

In [ ]:
solution = solve(U_matrix-U, [phi1, phi2, phi3, phi4, phi5, theta1, theta2, theta3])

In [ ]:
solution[phi1]

In [ ]:
solution[phi1]

In [2]:
state_0 = [[1], [0], [0]]
state_1 = [[0], [1], [0]]
state_2 = [[0], [0], [1]]

In [24]:
A = state_0@np.transpose(state_1) + state_1@np.transpose(state_2) + state_2@np.transpose(state_0) #state_0@np.transpose(state_1) + state_2@np.transpose(state_2)

In [26]:
X01 = np.array([[0, 1, 0],
                [1, 0, 0],
                [0, 0, 1]])
X12 = np.array([[1, 0, 0],
                [0, 0, 1],
                [0, 1, 0]])

In [36]:
state00 = np.kron(state_0, state_0)
state01 = np.kron(state_0, state_1)
state02 = np.kron(state_0, state_2)
state10 = np.kron(state_1, state_0)
state11 = np.kron(state_1, state_1)
state12 = np.kron(state_1, state_2)
state20 = np.kron(state_2, state_0)
state21 = np.kron(state_2, state_1)
state22 = np.kron(state_2, state_2)

In [39]:
B = 0.5*(state00@np.transpose(state00)) + 0.5*(state22@np.transpose(state22))

In [45]:
np.trace(state00@np.transpose(state00)@B)

0.5

In [64]:
q0 = state_0
q1 = state_0
#q2 = state_0

first = (state_0@np.transpose(state_0)@ q0) + (state_1@np.transpose(state_1) @ q0) + (state_2@np.transpose(state_2) @ q0)
second = np.eye(3)@q1 + (X12@X01)@q1 + (X01@X12)@q1
state = np.kron(first, second)

In [65]:
state

array([[1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [40]:
C = np.kron(state_0@np.transpose(state_0), np.eye(3)) +\
np.kron(state_1@np.transpose(state_1), X01@X12) +\
np.kron(state_2@np.transpose(state_2), X12@X01)

In [13]:
CNOT = state00@np.transpose(state00) +\
state01@np.transpose(state01) +\
state02@np.transpose(state02) +\
state10@np.transpose(state12) +\
state11@np.transpose(state10) +\
state12@np.transpose(state11) +\
state20@np.transpose(state21) +\
state21@np.transpose(state22) +\
state22@np.transpose(state20)

In [14]:
CNOT

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0]])

In [18]:
def U_D(phi_i, phi_j, phi_k):
    return np.array([[np.exp(1j*phi_i), 0, 0],
                     [0, np.exp(1j*phi_j), 0],
                     [0, 0, np.exp(1j*phi_k)]])

In [19]:
def rx01(parameter):
    return np.array([[np.cos(parameter / 2), -1j * np.sin(parameter / 2), 0],
                    [-1j * np.sin(parameter / 2), np.cos(parameter / 2), 0],
                    [0, 0, 1]])

In [20]:
def rx12(parameter):
    return np.array([[1, 0, 0],
                    [0, np.cos(parameter / 2), -1j * np.sin(parameter / 2)],
                    [0, -1j * np.sin(parameter / 2), np.cos(parameter / 2)]])

In [21]:
def P01(parameter):
    return np.array([[np.exp(1j*parameter), 0, 0],
                    [0, 1, 0],
                    [0, 0, 1]])

In [22]:
def P12(parameter):
    return np.array([[1, 0, 0],
                    [0, 1, 0],
                    [0, 0, np.exp(1j*parameter)]])

In [23]:
def R_01_offset(theta, phi):
    return P01(-phi)@rx01(theta)@P01(phi)

In [24]:
def R_12_offset(theta, phi):
    return P12(phi)@rx12(theta)@P12(-phi)

In [17]:
def get_parameter(U):
    if abs(np.absolute(U[2, 2]) - 1) < 1e-6:
        theta_1 = phi_1 = theta_2 = phi_2 = 0
        phi_4 = np.angle(U[2, 2])
        phi_5 = np.angle(U[1, 1])
        phi_6 = np.angle(U[0, 0])
        # phi_3 = phi_6 - pi/2 - np.angle(U[0, 1])
        phi_3 = np.angle(U[1, 0]) - phi_5 + pi/2
        theta_3 = 2*np.arccos(np.absolute(U[1, 1]))
    else:
        phi_4 = np.angle(U[2, 2])
        theta_2 = 2*np.arccos(np.round(np.absolute(U[2, 2]), 6))
        phi_2 = np.angle(U[2, 1]) - phi_4 + pi/2
        phi_1 = np.angle(-U[2, 0]) - phi_2 - phi_4
        theta_1 = 2*np.arccos(np.round(np.absolute(U[2, 1])/np.sin(theta_2/2), 6))
        theta_3 = 2*np.arccos(np.round(np.absolute(U[1, 2])/np.sin(theta_2/2), 6))
        phi_5 = np.angle(U[1, 2]) + phi_2 + pi/2
        phi_3 = np.angle(np.cos(theta_1/2) * np.cos(theta_2/2) * np.cos(theta_3/2) - U[1, 1]*np.exp(-1j*phi_5)) + phi_1
        phi_6 = np.angle(-U[0, 2]) + phi_3 + phi_2
    return theta_1, theta_2, theta_3, phi_1, phi_2, phi_3, phi_4, phi_5, phi_6

def reconstruct(theta_1, theta_2, theta_3, phi_1, phi_2, phi_3, phi_4, phi_5, phi_6):
    return U_d(phi_6, phi_5, phi_4) @ R01(phi_3, theta_3) @ R12(phi_2, theta_2) @ R01(phi_1, theta_1)