In [1]:
import numpy as np

array([[0],
       [0],
       [1]])

In [1]:
print(r'$|0\rangle$')

$|0\rangle$


In [2]:
state_0 = [[1], [0], [0]]
state_1 = [[0], [1], [0]]
state_2 = [[0], [0], [1]]

In [24]:
A = state_0@np.transpose(state_1) + state_1@np.transpose(state_2) + state_2@np.transpose(state_0) #state_0@np.transpose(state_1) + state_2@np.transpose(state_2)

In [30]:
state_0

array([[0, 1, 0],
       [0, 0, 1],
       [1, 0, 0]])

In [32]:
p_meas = 0.001
error_meas = [('x+', p_meas/2), ('x-', p_meas/2), ('I', 1-p_meas)]

In [34]:
probs = [error_meas[i][1] for i in range(3)]

In [35]:
probs

[0.0005, 0.0005, 0.999]

In [26]:
X01 = np.array([[0, 1, 0],
                [1, 0, 0],
                [0, 0, 1]])
X12 = np.array([[1, 0, 0],
                [0, 0, 1],
                [0, 1, 0]])

In [36]:
state00 = np.kron(state_0, state_0)
state01 = np.kron(state_0, state_1)
state02 = np.kron(state_0, state_2)
state10 = np.kron(state_1, state_0)
state11 = np.kron(state_1, state_1)
state12 = np.kron(state_1, state_2)
state20 = np.kron(state_2, state_0)
state21 = np.kron(state_2, state_1)
state22 = np.kron(state_2, state_2)

In [39]:
B = 0.5*(state00@np.transpose(state00)) + 0.5*(state22@np.transpose(state22))

In [45]:
np.trace(state00@np.transpose(state00)@B)

0.5

In [64]:
q0 = state_0
q1 = state_0
#q2 = state_0

first = (state_0@np.transpose(state_0)@ q0) + (state_1@np.transpose(state_1) @ q0) + (state_2@np.transpose(state_2) @ q0)
second = np.eye(3)@q1 + (X12@X01)@q1 + (X01@X12)@q1
state = np.kron(first, second)

In [65]:
state

array([[1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [40]:
C = np.kron(state_0@np.transpose(state_0), np.eye(3)) +\
np.kron(state_1@np.transpose(state_1), X01@X12) +\
np.kron(state_2@np.transpose(state_2), X12@X01)

array([[0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [22]:
state00@np.transpose(state00)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [20]:
C@state00

array([[1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.]])

In [13]:
CNOT = state00@np.transpose(state00) +\
state01@np.transpose(state01) +\
state02@np.transpose(state02) +\
state10@np.transpose(state12) +\
state11@np.transpose(state10) +\
state12@np.transpose(state11) +\
state20@np.transpose(state21) +\
state21@np.transpose(state22) +\
state22@np.transpose(state20)

In [14]:
CNOT

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0]])

In [100]:
def square(x):
    """Square of x."""
    return x*x

def cube(x):
    """Cube of x."""
    return x(5)

In [101]:
cube(square)

25